//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DokterPraktekV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminMedicineController
    {
        public int ID { get; set; }
        public string StatusSecureText { get; set; }
        public string StatusExpiredText { get; set; }
        public int ExpiredDateRange { get; set; }
    }
}
