//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DokterPraktekV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class doctor
    {
        public int id { get; set; }
        public string name { get; set; }
        public string homeAddress { get; set; }
        public bool gender { get; set; }
        public string phone { get; set; }
        public byte[] registerDatetime { get; set; }
        public string userId { get; set; }
    }
}
